# This file stores configurations for your Shopify app.

scopes = "write_products,read_themes,read_products,write_script_tags,write_themes,read_themes,read_own_subscription_contracts,write_own_subscription_contracts,read_orders,read_customers"
